services:
  - type: web
    name: career-recommendation-api
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn main_app:app --host 0.0.0.0 --port $PORT
